//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDDMTools.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alignment> Alignments { get; set; }
        public virtual DbSet<Background> Backgrounds { get; set; }
        public virtual DbSet<Bond> Bonds { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassFeature> ClassFeatures { get; set; }
        public virtual DbSet<DonDoff> DonDoffs { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<FirstName> FirstNames { get; set; }
        public virtual DbSet<Flaw> Flaws { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Height> Heights { get; set; }
        public virtual DbSet<Ideal> Ideals { get; set; }
        public virtual DbSet<LastName> LastNames { get; set; }
        public virtual DbSet<PersonalityTrait> PersonalityTraits { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Proficiency> Proficiencies { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Speed> Speeds { get; set; }
        public virtual DbSet<SubRace> SubRaces { get; set; }
        public virtual DbSet<Weapon> Weapons { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
        public virtual DbSet<WholeName> WholeNames { get; set; }
    }
}
