//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDDMTools.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cost { get; set; }
        public Nullable<int> AC { get; set; }
        public string ACDesc { get; set; }
        public Nullable<int> StrReq { get; set; }
        public Nullable<bool> StealthDisadvantage { get; set; }
        public string Weight { get; set; }
        public Nullable<int> DonDoffId { get; set; }
        public string Description { get; set; }
    
        public virtual DonDoff DonDoff { get; set; }
    }
}
