//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDDMTools.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Height
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Height()
        {
            this.SubRaces = new HashSet<SubRace>();
        }
    
        public int Id { get; set; }
        public string MaxFoot { get; set; }
        public string MaxInch { get; set; }
        public string MinFoot { get; set; }
        public string MinInch { get; set; }
        public int RaceId { get; set; }
    
        public virtual Race Race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubRace> SubRaces { get; set; }
    }
}
