//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDDMTools.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public int SubRaceId { get; set; }
        public int MainClassId { get; set; }
        public int MainClassLevel { get; set; }
        public Nullable<int> SubClassId { get; set; }
        public Nullable<int> SubClassLevel { get; set; }
        public Nullable<int> TertiaryClassId { get; set; }
        public Nullable<int> TertiaryClassLevel { get; set; }
        public int WholeNameId { get; set; }
        public int GenderId { get; set; }
        public int AlignmentId { get; set; }
        public int StrAbility { get; set; }
        public int DexAbility { get; set; }
        public int ConAbility { get; set; }
        public int IntAbility { get; set; }
        public int WisAbility { get; set; }
        public int ChaAbility { get; set; }
        public Nullable<int> PersonalityTraitId { get; set; }
        public Nullable<int> IdealId { get; set; }
        public Nullable<int> BondId { get; set; }
        public Nullable<int> FlawId { get; set; }
        public Nullable<int> BackgroundId { get; set; }
    
        public virtual Alignment Alignment { get; set; }
        public virtual Background Background { get; set; }
        public virtual Bond Bond { get; set; }
        public virtual Class Class { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual Class Class2 { get; set; }
        public virtual Flaw Flaw { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Ideal Ideal { get; set; }
        public virtual PersonalityTrait PersonalityTrait { get; set; }
        public virtual WholeName WholeName { get; set; }
    }
}
