//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDDMTools.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRace
    {
        public int Id { get; set; }
        public int STRMod { get; set; }
        public int DEXMod { get; set; }
        public int CONMod { get; set; }
        public int INTMod { get; set; }
        public int WISMod { get; set; }
        public int CHAMod { get; set; }
        public int HeightId { get; set; }
        public int SizeId { get; set; }
        public int WeightId { get; set; }
        public int SpeedId { get; set; }
        public int RaceId { get; set; }
    
        public virtual Height Height { get; set; }
        public virtual Race Race { get; set; }
        public virtual Size Size { get; set; }
        public virtual Speed Speed { get; set; }
        public virtual Weight Weight { get; set; }
    }
}
