//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDDMTools.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        public int Id { get; set; }
        public string Weapon1 { get; set; }
        public string Cost { get; set; }
        public string Damage { get; set; }
        public string Weight { get; set; }
        public Nullable<int> PropertyId { get; set; }
    }
}
